#! /bin/bash
 
# originaly from http://tinyurl.com/twitch-linux from taladan
# www.youtube.com/user/taladan
 
# gist created by brodul
 
INRES="1280x1024" # input resolution (The resolution of the program you want to stream!)
OUTRES="1280x720" # Output resolution (The resolution you want your stream to be at)
FPS="30" # target FPS
QUAL="medium" 
# one of the many FFMPEG preset on (k)ubuntu found in /usr/share/ffmpeg
# If you have low bandwidth, put the qual preset on 'fast' (upload bandwidth)
# If you have medium bandwitch put it on normal to medium
 
# Write your key in a file named .twitch_key in your home directory
STREAM_KEY=$(cat ~/.twitch_key) # This is your streamkey generated by jtv/twitch found at: http://www.justin.tv/broadcast/adv_other
 
avconv \
-f x11grab -s $INRES -r "$FPS" -i :0.0 \
-f alsa -ac 2 \
-vcodec libx264 -s $OUTRES -preset $QUAL \
-acodec libmp3lame -ar 44100 \
-threads 6 -qscale 3 -b 712000 -bufsize 512k \
-f flv "rtmp://live.justin.tv/app/$STREAM_KEY"
