# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "EveryonePlaysPokemon" do
  pod 'FormatterKit'
  pod 'AFNetworking', :git => "git@github.com:tracervision/AFNetworking.git"
end

target "EveryonePlaysPokemonTests" do

end

